local_backend:
  url: http://localhost:8082/api/v1

backend:
  name: git-gateway
  branch: main
  quash_merges: true

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images/"

collections:
  - name: "admin"
    label: "Admin"
    files:
      - file: "src/data/site-details.json"
        name: "site-details"
        label: "Site details"
        fields:
          - { label: "Publication name", name: "name", widget: "string" }
          - { label: "Parent organisation", name: "parentOrganization", widget: "string" }
          - { label: "Descriptions", name: "description", widget: "string" }
          - { label: "Year founded", name: "yearFounded", widget: "number" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Support link", name: "supportLink", widget: "string" }
          - { label: "Site logo", name: "logoUrl", widget: "image" }
          - { label: "Site emblem", name: "emblemUrl", widget: "image" }
          - { label: "Site favicon", name: "faviconUrl", widget: "image" }
          - { label: "Sections", name: "sections", widget: "list", fields: [{ label: "Name", name: "label", widget: "string" }, { label: "Slug", name: "slug", widget: "string" }] }
      - file: "src/data/navigation.json"
        name: "navigation"
        label: "Navigation"
        fields:
          - { label: "Header", name: "header", widget: "list", fields: [{ label: "Label", name: "label", widget: "string" }, { label: "URL", name: "url", widget: "string" }, { label: "Sub navigation", name: "subNav", widget: "list", fields: [{ label: "Label", name: "label", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }] }
          - { label: "Footer", name: "footer", widget: "list", fields: [{ label: "Label", name: "label", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }
  - name: "articles"
    label: "Articles"
    folder: "src/data/articles" 
    create: true
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    slug: "{{fields.slug}}"
    sortable_fields: ["publicationDate", "title"]
    fields:
      - { label: "Slug", name: "slug", widget: "string", hint: "Sets the url e.g. yoursite.com/section/**your-slug-here**" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured image", name: "featuredImage", widget: "image" }
      - { label: "Featured image alt text", name: "featuredImageAltText", widget: "string" }
      - { label: "Featured image caption", name: "featuredImageCaption", widget: "string" }
      - { label: "Publication date", name: "publicationDate", widget: "datetime" }
      - { label: "Authors", name: "authors", widget: "list", fields: [{ label: "Author", name: "slug", widget: "relation", collection: "authors", searchFields: ["name"], valueField: "slug" }] }
      - { label: "Section", name: "section", widget: "select", options: ["new-town", "business-district", "old-town"] }
      - { label: "Tags", name: "tags", widget: "list", fields: [{label: "Tag", name: "tag", widget: "string"}] }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "authors"
    label: "Authors"
    folder: "src/data/authors"
    create: true
    slug: "{{fields.slug}}"
    format: "json"
    fields:
      - { label: "ID", name: "slug", widget: "string", hint: "Unique author identifier, also sets the author page url e.g. yoursite.com/authors/**author-id**" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown", required: false }
